[server]
headless = true
address = "0.0.0.0"
port = 8501
enableWebsocketCompression = true
maxUploadSize = 400
maxMessageSize = 2048

[theme]
# Main accent (button) color - this is the classic Streamlit red
primaryColor = "#FF4B4B"

# Page background (outer area)
backgroundColor = "#020617"          # very dark blue/black

# Cards / sidebars background
secondaryBackgroundColor = "#1F2933" # brighter cards

# Text color
textColor = "#FFFFFF"

# Optional: font
font = "sans serif"

[ui]
hideTopBar = false

[client]
toolbarMode = "viewer"
